LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
	rkunpack.c

#LOCAL_C_INCLUDES := $(LOCAL_PATH)/popt

LOCAL_CFLAGS := -DHAVE_CONFIG_H

LOCAL_MODULE := rkunpack
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE_TAGS := eng

include $(BUILD_EXECUTABLE)
